# Generated by Django 5.2.8 on 2025-11-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('comprador', 'Comprador'), ('arrendatario', 'Arrendatario'), ('vendedor', 'Vendedor'), ('propietario', 'Propietario')], max_length=20)),
                ('rango_precio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rango_precio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comunas_interes', models.TextField(blank=True, help_text='Comunas de interés separadas por comas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('tipo_propiedad_interes', models.ManyToManyField(blank=True, to='propiedades.tipopropiedad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='InteresPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_interes', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('contactado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Interés en Propiedad',
                'verbose_name_plural': 'Intereses en Propiedades',
                'unique_together': {('cliente', 'propiedad')},
            },
        ),
    ]
