# Generated by Django 5.2.8 on 2025-11-18 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono', max_length=30)),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Propiedad',
                'verbose_name_plural': 'Tipos de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_operacion', models.CharField(choices=[('venta', 'Venta'), ('arriendo', 'Arriendo'), ('venta_arriendo', 'Venta o Arriendo')], max_length=20)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_arriendo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0, verbose_name='Baños')),
                ('estacionamientos', models.IntegerField(default=0)),
                ('superficie_total', models.IntegerField(help_text='Superficie en metros cuadrados')),
                ('superficie_construida', models.IntegerField(blank=True, help_text='Superficie construida en metros cuadrados', null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendida', 'Vendida'), ('arrendada', 'Arrendada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('visitas', models.IntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentes.agente')),
                ('caracteristicas', models.ManyToManyField(blank=True, to='propiedades.caracteristica')),
                ('tipo_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='propiedades.tipopropiedad')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-destacado', '-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/%Y/%m/')),
                ('orden', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.propiedad')),
            ],
            options={
                'verbose_name': 'Imagen de Propiedad',
                'verbose_name_plural': 'Imágenes de Propiedades',
                'ordering': ['orden'],
            },
        ),
    ]
